name: Run Unit Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [inventory-service]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and run tests
        working-directory: ${{ matrix.service }}
        run: |
          npm install
          npm test
